Refactor SIP stress testing and introduce performance tests (untested)

diff --git a/debian/clearwater-sip-perf.postinst b/debian/clearwater-sip-perf.postinst
--- a/debian/clearwater-sip-perf.postinst
+++ b/debian/clearwater-sip-perf.postinst
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# @file clearwater-sip-stress.prerm
+# @file clearwater-sip-perf.postinst
 #
 # Project Clearwater - IMS in the Cloud
 # Copyright (C) 2013  Metaswitch Networks Ltd
@@ -40,52 +40,33 @@
 set -e
 
 # summary of how this script can be called:
-#        * <prerm> `remove'
-#        * <old-prerm> `upgrade' <new-version>
-#        * <new-prerm> `failed-upgrade' <old-version>
-#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
-#        * <deconfigured's-prerm> `deconfigure' `in-favour'
-#          <package-being-installed> <version> `removing'
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-NAME=clearwater-sip-stress
-log_directory=/var/log/$NAME
-
-#
-# These functions undo their counterparts in bono.postinst
-#
-remove_logging() {
-    if [ -d "$log_directory" ]; then
-        rm -r $log_directory
-    fi
-}
-
-remove_section() {
-  file=$1
-  tag=$2
-  awk '/^#\+'$tag'$/,/^#-'$tag'$/ {next} {print}' $file >/tmp/$(basename $file).$$
-  mv /tmp/$(basename $file).$$ $file
-}
+NAME=clearwater-sip-perf
 
 case "$1" in
-    remove|upgrade|deconfigure)
-        remove_logging
-
-        remove_section /etc/sysctl.conf clearwater-sip-stress
-        sysctl -p /etc/sysctl.conf >/dev/null
+    configure)
+        /usr/share/clearwater/infrastructure/scripts/sip-perf
+        # Don't start the service - we do this on demand
     ;;
 
-    failed-upgrade)
+    abort-upgrade|abort-remove|abort-deconfigure)
     ;;
 
     *)
-        echo "prerm called with unknown argument \`$1'" >&2
+        echo "postinst called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
-
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
