Build sprout-base and plug-ins as separate packages

diff --git a/debian/sprout-icscf.postinst b/debian/sprout-icscf.postinst
--- a/debian/sprout-icscf.postinst
+++ b/debian/sprout-icscf.postinst
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# @file sprout.postrm
+# @file sprout-icscf.postinst
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2013  Metaswitch Networks Ltd
+# Copyright (C) 2014  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -39,13 +39,34 @@
 
 set -e
 
-# Call into clearwater-logging-update to update logging now that we've removed
-# removing configuration files.
-[ ! -x /usr/share/clearwater/bin/clearwater-logging-update ] || /usr/share/clearwater/bin/clearwater-logging-update
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
+case "$1" in
+    configure)
+        # Restart sprout to force reload of new plug-in.  Always do this by
+        # terminating sprout so monit will restart it more-or-less immediately.
+        # (monit restart seems to have significant lag.)
+        # Don't fail if it's already stopped.
+        service sprout stop || /bin/true
+    ;;
 
-#DEBHELPER#
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
 exit 0
diff --git a/debian/sprout-mmtel-as.prerm b/debian/sprout-mmtel-as.prerm
--- a/debian/sprout-mmtel-as.prerm
+++ b/debian/sprout-mmtel-as.prerm
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# @file sprout.postinst
+# @file sprout-mmtel-as.prerm
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2013  Metaswitch Networks Ltd
+# Copyright (C) 2014  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -40,73 +40,27 @@
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-NAME=sprout
-log_directory=/var/log/$NAME
-
-add_section() {
-    file=$1
-    tag=$2
-    delta=$3
-    { echo "#+$tag"
-      cat $delta
-      echo "#-$tag" ; } >> $file
-}
-
-#
-# Function to set up the user account for the daemon
-#
-setup_user() {
-    if ! grep -q "^$NAME:" /etc/passwd ; then useradd --system -M -d /nonexistent -s /bin/false $NAME ; fi
-}
-
-#
-# Function to ensure logging directory is in place and has the right permissions
-#
-setup_logging() {
-    if [ ! -d "$log_directory" ]; then
-        mkdir -p $log_directory
-        chown $NAME $log_directory
-    fi
-}
-
 case "$1" in
-    configure)
-        setup_user
-        setup_logging
-        [ ! -x /usr/share/clearwater/bin/clearwater-logging-update ] || /usr/share/clearwater/bin/clearwater-logging-update
-        add_section /etc/security/limits.conf sprout /etc/security/limits.conf.sprout
-        /usr/share/clearwater/infrastructure/scripts/sprout.monit
-
-        # Restart sprout.  Always do this by terminating sprout so monit will
-        # restart it more-or-less immediately.  (monit restart seems to have
-        # significant lag.)
-        # Don't fail if it's already stopped.
-        service sprout stop || /bin/true
+    remove|upgrade|deconfigure)
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
 
 exit 0
