Markup: exit validation if it fails, bash script prints error message and exit

diff --git a/sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json b/sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json
--- a/sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json
+++ b/sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json
@@ -16,6 +16,13 @@ SCHEMA=/usr/share/clearwater/clearwater-config-manager/scripts/config_validation
 # Validate config json against schema for syntactic errors
 python /usr/share/clearwater/clearwater-config-manager/scripts/validate_config.py $SCHEMA $FILENAME 
 
+# Abort uploading and warn user if validation fails
+rc=$?
+if [[ $rc != 0 ]]; then
+  echo "Abort uploading $FILENAME, pls fix syntax and upload again"
+  return $rc
+fi
+
 # Pass optional argument directly to upload_json, which checks for --allow-large
 # option that allows file upload larger than advisable
 /usr/share/clearwater/clearwater-config-manager/scripts/upload_json $FILENAME $KEY $1
